### ISSUE TITLE
Missing files to build

### ISSUE THREAD

**Issue by Ramblurr** [invizbox/invizbox-go#2]
The provided makefiles are including and referencing files that are not included in the repo. Specifically:

* `rules.mk`
* `package.mk`

**Comment by VincentRiou** [comment]
Hi @Ramblurr,
these files are part of lede (see our fork of lede at https://github.com/invizbox/lede). LEDE is the build system and ultimately the invizbox-go repository is mostly a feed reporitory.
If you want to understand more about it, you will have to familiarise yourself with lede.
As mention in #1, I'll work towards being able to build from github.

I'll consider this one as closed since the files have been found.

**Comment by invizbox** [comment]
https://github.com/invizbox/lede/blob/InvizBox_Go_2.x/rules.mk
https://github.com/invizbox/lede/blob/InvizBox_Go_2.x/include/package.mk

**Comment by Ramblurr** [comment]
Thanks @VincentRiou !
